### ISSUE TITLE
Issue with manifest.yml file

### ISSUE THREAD

**Issue by hobertbush** [watson-developer-cloud/visual-recognition-nodejs#193]
The manifest.yml file is missing a ":" on line 3 of the declared-service name "visual-recognition-free"

```
    ---
declared-services:
  visual-recognition-free
    label: watson_vision_combined
    plan: free
applications:
- services:
  - visual-recognition-free
  name: visual-recognition-demo
  command: npm start
  path: .
  memory: 512M
```
Should be defined as the following:

```
    ---
declared-services:
  visual-recognition-free:
    label: watson_vision_combined
    plan: free
applications:
- services:
  - visual-recognition-free
  name: visual-recognition-demo
  command: npm start
  path: .
  memory: 512M
```
